version: '3.7'
services:
  postgresql:
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
